### ISSUE TITLE
Just saw the video on YT, love the project, can you give me some primers on how to implement this myself?

### ISSUE THREAD

**Issue by ghost** [omggomb/GodotPhysXPrototype#2]
Hi! I'm fairly new to Godot and like you, I want to extend the engine. I've already been able to figure out what you did was compile PhysX as a shared/dynamic library, and you then somehow used GDNative to interface with it, but is there something else I should know before attempting this? 

For example:

- Did you extend PhysicsServer at all? If not, is it feasible to do it?

- What are the drawbacks of your specific implementation? How easy is it to interface with the rest of Godot? How do you interface with it, is there something special besides just using GDNative (just the gist of it)?

- In the NativeLibraryImpl/bin folder, what is the libsimple.dll file? I assume the init.cpp file is the cpp file used to actually link PhysX and Godot?

I'm aware some of these questions are probably things I should already know if I want to do this, but although I'm experienced with gamedev I am fairly new to Godot and this way to do things. Thank you for your time anyway!

**Comment by omggomb** [comment]
Thanks! 

1: No I didn't implement this as physics server. That would be the proper way though. I can't help you with that though, as I have no idea how that works. AFAIK the problem will also be that GDNative doesn't allow to extend the PhysicsServer. You'd need create a [module](https://docs.godotengine.org/en/stable/development/cpp/custom_modules_in_cpp.html) for that. Or use the 4.0 alpha and use GDExtension but documentation on GDExtension is scarce. 

I would ask around in the [contributors chat](https://chat.godotengine.org/), there should be a channel for physics. I bet there is some interest to actually pull this of as a 4.0 extension, since it's asked for quite regularly. 

2: What I did was create an instance in the VisualServer and the respective physical body in the PhysX simulation. Then every frame I just get all of the rigid bodies of the PhysX simulation, find out which visual instance belongs to them and update their transforms in the visual server. The magic happens in the `_process` function, specifically [this](https://github.com/omggomb/GodotPhysXPrototype/blob/master/NativeLibraryImpl/src/init.cpp#L132) line. 

So the drawback is first and foremost, that it is not integrated with the PhysicsServer and therefore can't be used with Godot's nodes. It's also incomplete. It really is just the bare minimum to proof that PhysX is faster than Bullet and Godot's built in physics. I did this because of another YT video that compared Godot to Unity, which is hardly fair since Unity uses PhysX and therefore will win. Remember: The point of my video was to show that these "benchmarks" are rubbish and only measure physics performance and only do so in a very specific scenario.

3: libsimple.dll is the compiled GDNative library that Godot will load. It is created from init.cpp . Indeed init.cpp is the glue between Godot and PhysX. I can't remember why I called it libsimple, sorry. It was supposed to be quick and dirty implementation after all.

Hoped that helped a bit!

**Comment by ghost** [comment]
Hey! Thanks for replying, your replies pretty much explained everything. 

I asked in the contributors chat and people mentioned this should be possible with GDExtension eventually but at least one person reported a showstopper problem trying to register classes as a module. That same person pointed out this project that also tried to integrate PhysX as a module - https://github.com/nekomatata/godot/tree/_wip_physx - though this is going to be out of date.

And I see the problems, one really does need to include PhysX as a core module at least for now if you want to integrate it with Godot.
